### PR TITLE
Adding Translations

### PR DESCRIPTION
**Pull request by RomuloGatto**
Adding the following translations to the system:

- Portuguese (Brazil)
- Spanish (Spain)

### CODE REVIEW

**Comment by iMaiconP** [comment]
Hi. Are these translations still working? I'm about to use this with my wife, but I haven't installed just yet. Just wondering, because she only speaks Portuguese. And I didn't see the language on readme. Maybe it got discarded with the launch of V2?

**Comment by tech-kev** [comment]
Hi @iMaiconP,
Unfortunately, with the release of V2 there were so many breaking changes that basically all texts were rewritten. For that reason, all existing translations (including Portuguese) are currently outdated and not included anymore.

If you would like to contribute a Portuguese translation, you're more than welcome! You can find all the information on how to do it here: https://github.com/tech-kev/SharedMoments/wiki/Translation

I'm happy to help if you have any questions! 😊

**Comment by iMaiconP** [comment]
Hey, thanks for the fast reply @tech-kev . I'll wait to see if @RomuloGatto wants to do it. For now, I'll start locally translating my instance as soon as I install this. If he doesn't say anything, then I'll make my own PR.

**Comment by RomuloGatto** [comment]
@iMaiconP I used it for my wedding only, feel free to take ownership on the translations

**Pull request merged**
